sudo: required
services:
    - docker

before_install:
        - docker build -t edraobdu/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true edraobdu/react-test npm test

after_success:
    - docker build -t edraobdu/multi-client ./client
    - docker build -t edraobdu/multi-nginx ./nginx
    - docker build -t edraobdu/multi-server ./server
    - docker build -t edraobdu/multi-worker ./worker

    # Log in to the docekr CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push edraobdu/multi-client
    - docker push edraobdu/multi-nginx
    - docker push edraobdu/multi-server
    - docker push edraobdu/multi-worker

# deploy:
#     edge: true
#     provider: elasticbeanstalk
#     region: us-west-1
#     app: multi-docker
#     env: MultiDocker-env
#     bucket_name: elasticbeanstalk-us-west-1-306476627547
#     bucket_path: docker-multi
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
